### ISSUE TITLE
No module named 'numpy.typing'

### ISSUE THREAD

**Issue by CarinaFo** [mne-tools/mne-icalabel#114]
mne-icalabel 0.4 
mne  1.1.1
linux

error occurs while importing mne-icalabel

**Comment by jacobf18** [comment]
@CarinaFo which version of numpy do you have installed?

**Comment by mscheltienne** [comment]
Anyway, there is an error on our side. `numpy.typing` was introduced in 1.20, and `numpy.typing.NDArray` in 1.21.
And we have a requirement of 1.16 https://github.com/mne-tools/mne-icalabel/blob/97f2438c4221bab050ba9357e18b8980e2987391/pyproject.toml#L40

I fixed the requirement in 2a201830e46c5a021dd7d9f0c13de10887c68a8f
