### ISSUE TITLE
Example render for 0.4 stable website

### ISSUE THREAD

**Issue by mscheltienne** [mne-tools/mne-icalabel#117]
The examples did not render on the stable version of the doc: https://mne.tools/mne-icalabel/stable/auto_examples/index.html
It would be good to checkout the 0.4.0 version, rebuild the doc locally, and upload it on the gh-pages branch in the correct directory.

**Comment by mscheltienne** [comment]
The filename pattern to execute the sphinx-gallery examples does not make sense to me: https://github.com/mne-tools/mne-icalabel/blob/34a896effe0851da1b5fd6b6c30e7cf9c792e3db/doc/conf.py#L258

We could probably change the example names to a `XX_name` format with `XX` 2 numbersm e.g. `00_`, `10_`, `20_` as for the MNE tutorials.
-> Helps to sort the examples.
-> Retains the possibility to add examples in-between 2 other examples, e.g. `05_`

The pattern would become: `"filename_pattern": r"\d{2}_"`.

**Comment by adam2392** [comment]
Yeah I think I copied it over originally so I'm +1 for simplifying.

**Comment by mscheltienne** [comment]
I re-build and re-uploaded the 0.4 doc from the maint/0.4 branch, it build without warning, examples were executed, and it looked good locally, but it's messed up on the deployment. I'll try again later.
