### ISSUE TITLE
ValueError: need at least one array to concatenate

### ISSUE THREAD

**Issue by finch-f** [mne-tools/mne-icalabel#123]
After I run the following codes, I met this error.

from mne_icalabel import label_components
ic_labels = label_components(epochs, ica, method="iclabel")
print(pd.DataFrame(ic_labels))

My data type is MEG data. So is it possible that the icalabel is not suite for MEG data?

Thanks for your time~

**Comment by mscheltienne** [comment]
It's definitely not suited for MEG data, ICLabel was trained on EEG data.

Could you still post the full traceback of this error, to check if it's due to the selection of EEG channels that yielded nothing or to something else?

Mathieu

**Comment by finch-f** [comment]
Thank you for your reply. Now I see why my code did not work.

Below is the traceback of this error. 

![image](https://user-images.githubusercontent.com/39895713/219680281-07f715c2-aa1b-46d3-9a8d-ce3993a06c78.png)

**Comment by adam2392** [comment]
Perhaps we can have an error message if there are no eeg type channels selected?

**Comment by mscheltienne** [comment]
Yes, we should, I just wanted to make sure that the error raised was due to the lack of EEG channels, and it is!

**Comment by mscheltienne** [comment]
MRE:

```
from mne.datasets import sample
from mne.io import read_raw_fif
from mne.preprocessing import ICA
from mne_icalabel import label_components


directory = sample.data_path() / "MEG" / "sample"
raw = read_raw_fif(directory / "sample_audvis_raw.fif", preload=False)
raw.pick_types(meg=True)
raw.load_data()
raw.filter(1., 100.)
ica = ICA(n_components=5, method="picard")
ica.fit(raw)

labels = label_components(raw, ica, method="iclabel")
```

**Comment by finch-f** [comment]
Many thanks. I think rasing an error of no EEG channels selected is very helpful~
