### ISSUE TITLE
ONNX/Tensorflow Port

### ISSUE THREAD

**Issue by jacobf18** [mne-tools/mne-icalabel#125]
I just wanted to inform everybody that I was working on porting the PyTorch code to work with other deep-learning frameworks. I am doing this because PyTorch doesn't work well with other python packages for bundling into standalone programs. Also, PyTorch is large compared to other packages like ONNX when all we are doing is inference. The changes are minor and restricted to the `network.py` file.

We could make it an option for which framework to use if people have trouble installing PyTorch or want to run this package on a system that cannot run PyTorch.

**Comment by mscheltienne** [comment]
That sounds like a great idea! I don't know ONNX, but I do like Tensorflow and Keras a lot :)
That might also make packaging simpler (or not?) especially when it comes to `conda-forge`.

**Comment by jacobf18** [comment]
ONNX is universal so it allows for porting to tensorflow/keras as well. From my initial tests, loading the ONNX runtime package is a lot faster than importing PyTorch.

**Comment by jacobf18** [comment]
Got it working on my laptop. Will format the code and push here soon. Also, if we wanted we could host the model using git LFS so that it wasn’t inside the repo. (It’s only 11 MB so this might not be necessary.) ONNX models can be loaded anywhere similar to PyTorch models with a `onnx.load` command (https://github.com/onnx/models)
