### ISSUE TITLE
Use of IClabel with MEG data. 

### ISSUE THREAD

**Issue by FedeC3N** [mne-tools/mne-icalabel#139]
Hi!

This is my first time writing in this forum, so I apologize beforehand if this is not the correct way for contacting the developers. 

I would like to ask for information about the use of IClabel with MEG data. I have been reading the issues and there is one issue (now closed) regarding this topic, but I can’t understand what was the final solution. 

Basically, my question is: is it possible to use IClabel with MEG data? Or is it planned to develop this feature?

Thanks for all the work!

Best regards,
Fede.

Ps: I’ve used IClabel with EEG label and it works perfectly!

**Comment by mscheltienne** [comment]
No, ICLabel is a network fitted on EEG data.
Thus, it's not designed to work on MEG data. If you want to add a different model, fitted and designed on MEG data, a PR would be welcome :)

**Comment by adam2392** [comment]
xref: #134
