### ISSUE TITLE
DOC: tables in dark mode are unreadable

### ISSUE THREAD

**Issue by scott-huberty** [mne-tools/mne-icalabel#144]
Due to a [bug](https://github.com/pydata/pydata-sphinx-theme/issues/1543) in `pydata_sphinx_theme` 0.14.2, in dark mode tables appear very light and with low contrast. I just noticed this is affecting the ICALabel docs:

![Screen Shot 2023-10-27 at 2 18 40 PM](https://github.com/mne-tools/mne-icalabel/assets/52462026/d942821b-0442-40f9-9eac-afbb6851199f)

I think a temporary fix for the mean time could be to pin to `pydata_sphinx_theme` 0.14.1 (in the doc building workflow), until they fix their bug. 

If you don't have the time I can submit a quick PR - just wanted to bring it to your attention!

**Comment by mscheltienne** [comment]
Thanks for the report and for finding the quick fix, let's wait for CIs to run, but the doc-build should finally work as intended (both light/dark theme and that forever broken version selection menu).
