### ISSUE TITLE
Outdated docs for label_components()

### ISSUE THREAD

**Issue by ScreamingPigeon** [mne-tools/mne-icalabel#150]
#### Describe the bug
The docs for [mne_icalabel.iclabel.label_components](https://mne.tools/mne-icalabel/stable/generated/api/mne_icalabel.iclabel.iclabel_label_components.html#mne_icalabel.iclabel.iclabel_label_components) seems to be outdated 

The API call seems to be `mne_icalabel.iclabel.label_components` and not  `mne_icalabel.iclabel.iclabel_label_components`

If I am correct, and the docs are incorrect, I would like to be assigned this issue. I can submit a PR to update the docs

**Comment by mscheltienne** [comment]
The doc is generated from the code (API). All good?
