### ISSUE TITLE
ICLabel Citation

### ISSUE THREAD

**Issue by lucapton** [mne-tools/mne-icalabel#212]
Would you mind adding the original paper to the requested citations in the "Citing" section of the readme file as well?

Thanks,
Luca

**Comment by mscheltienne** [comment]
@lucapton Done in #213, improving the visibility of ICLabel's original paper in (1) our readme and (2) our web documentation. Feel free to re-open if you think other actions should be taken.

**Comment by lucapton** [comment]
Thanks!On 18 Nov 2024, at 15:34, Mathieu Scheltienne ***@***.***> wrote:﻿
@lucapton Done in #213, improving the visibility of ICLabel's original paper in (1) our readme and (2) our web documentation. Feel free to re-open if you think other actions should be taken.
