### ISSUE TITLE
Inviting to mne-icalabel team

### ISSUE THREAD

**Issue by adam2392** [mne-tools/mne-icalabel#33]
Hi @agramfort is it easy to invite others, such as @mscheltienne  and @anandsaini024 and @jacobf18 to the mne-icalabel team for read/write access?

I don't think I can do so because no privileges.

**Comment by agramfort** [comment]
✅

**Comment by adam2392** [comment]
Are you also able to give me admin privileges on this repo so I can set things up like Zenodo and azure-pipelines?

**Comment by agramfort** [comment]
You should be a maintainer now. Let me know if you need admin.
