### ISSUE TITLE
reshape from epochs data shape

### ISSUE THREAD

**Issue by CarinaFo** [mne-tools/mne-icalabel#38]
#### Describe the bug

I want to use iclabel on mne.epochs but get an error message regarding the shape (it somehow neglects the channel dimension):

#### Steps to reproduce

epochss[0].shape 
epochss[0].get_data().shape
(719, 64, 751)

ic_labels = label_components(epochss[counter], icas[counter], method="iclabel")

Error msg:

<ipython-input-14-986a44b6c93e>:1: RuntimeWarning: The provided Epochs instance is not filtered between 1 and 100 Hz. ICLabel was designed to classify features extracted from an EEG dataset bandpass filtered between 1 and 100 Hz (see the 'filter()' method for Raw and Epochs instances).
  ic_labels = label_components(epochss[counter], icas[counter], method="iclabel")
C:\Users\Carina\Documents\expecon_EEG_analysis\venv\lib\site-packages\mne_icalabel\iclabel\utils.py:131: RuntimeWarning: divide by zero encountered in log
  g = np.square(d) * (np.log(d) - 1)  # % Green's function.
C:\Users\Carina\Documents\expecon_EEG_analysis\venv\lib\site-packages\mne_icalabel\iclabel\utils.py:131: RuntimeWarning: invalid value encountered in multiply
  g = np.square(d) * (np.log(d) - 1)  # % Green's function.
Traceback (most recent call last):
  File "C:\Users\Carina\Documents\expecon_EEG_analysis\venv\lib\site-packages\IPython\core\interactiveshell.py", line 3361, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-14-986a44b6c93e>", line 1, in <cell line: 1>
    ic_labels = label_components(epochss[counter], icas[counter], method="iclabel")
  File "C:\Users\Carina\Documents\expecon_EEG_analysis\venv\lib\site-packages\mne_icalabel\label_components.py", line 56, in label_components
    labels_pred_proba = methods[method](inst, ica)
  File "C:\Users\Carina\Documents\expecon_EEG_analysis\venv\lib\site-packages\mne_icalabel\iclabel\label_components.py", line 45, in iclabel_label_components
    features = get_iclabel_features(inst, ica)
  File "C:\Users\Carina\Documents\expecon_EEG_analysis\venv\lib\site-packages\mne_icalabel\iclabel\features.py", line 69, in get_iclabel_features
    psd = _eeg_rpsd(inst, ica, icaact)
  File "C:\Users\Carina\Documents\expecon_EEG_analysis\venv\lib\site-packages\mne_icalabel\iclabel\features.py", line 233, in _eeg_rpsd
    psd = _eeg_rpsd_compute_psdmed(inst, icaact, *constants)
  File "C:\Users\Carina\Documents\expecon_EEG_analysis\venv\lib\site-packages\mne_icalabel\iclabel\features.py", line 305, in _eeg_rpsd_compute_psdmed
    temp = temp.reshape(index.shape[0], len(inst), order="F")
ValueError: cannot reshape array of size 898750 into shape (250,719)

**Comment by adam2392** [comment]
What is `counter` and the `n_components` in your ICA?

**Comment by mscheltienne** [comment]
Could you explain how you create `epochss` and `icas`, which are I'm assuming list of Epochs instance and list of ICA instance?
`epochss[0]` seems to be an Epochs instance, so could you try:

```
from mne.preprocessing import ICA
from mne_icalabel import label_components

ica = ICA(n_components=0.99)  # 0.99 to speed-up
ica.fit(epochss[0])
labels = label_components(epochss[0], ica, method="iclabel")
```

**Comment by CarinaFo** [comment]
Yes, both lists contain the epochs I used to fit ICA and the fitted ICA per
subject. I save the data with pickle.
I tried what you suggested but get the same error, I don't think it is
related to the way I save the data.


Am Fr., 6. Mai 2022 um 19:58 Uhr schrieb Mathieu Scheltienne <
***@***.***>:

**Comment by mscheltienne** [comment]
Can you share one of the pickled files? 
By the way, epochs and ICA instances can be saved to `.fif` format with the method `.save()`.

**Comment by CarinaFo** [comment]
Sure, I converted now an instance of the fitte ICA and the epochs to .fif
files and zipped them.

I still get the same error, again indicating it is not related to the way I
save the data.

Best,

Carina
 test-ica.zip
<https://drive.google.com/file/d/1jevUpqMyB3HQAs8lDCZoJG1chOIJSZ4z/view?usp=drive_web>

Am Mo., 9. Mai 2022 um 10:40 Uhr schrieb Mathieu Scheltienne <
***@***.***>:

**Comment by mscheltienne** [comment]
Could you give me access to this drive on my Gmail account? You should have received a request.

**Comment by mscheltienne** [comment]
@CarinaFo up :)
Just in case, my Gmail account is mathieu.scheltienne@gmail.com

**Comment by mscheltienne** [comment]
Closing as outdated/stalled.
