### ISSUE TITLE
When viewing the stable docs, I see an (empty) changelog for the dev version

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-icalabel#39]
https://mne.tools/mne-icalabel/stable/whats_new.html
<img width="1021" alt="Screen Shot 2022-05-07 at 14 36 54" src="https://user-images.githubusercontent.com/2046265/167254745-db29281c-8860-4607-ab8f-af372bc33e2f.png">

**Comment by adam2392** [comment]
Ah did the docs deployment wrong :(

**Comment by adam2392** [comment]
Should be fixed now.
