### ISSUE TITLE
https://mne.tools/mne-icalabel doesn't redirect to the correct site

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-icalabel#44]
Instead, I end up here:
<img width="1440" alt="Screen Shot 2022-05-10 at 11 43 48" src="https://user-images.githubusercontent.com/2046265/167600146-93b51d5c-6044-4dd5-a682-cab6756e6b12.png">

https://mne.tools/mne-icalabel/stable/index.html OTOH works fine.

**Comment by adam2392** [comment]
Ooo good catch. I just pushed a change to `gh-pages`. Let's wait to see if it works...

**Comment by adam2392** [comment]
Not sure why it's still happening, but I deleted the gh-pages branch from my fork... Maybe that's what's causing the issue? Maybe it'll need to wait for GH to refresh end of day/hour(?)

**Comment by adam2392** [comment]
Giving my personal website additional hits I guess :p

**Comment by adam2392** [comment]
Still going there... not sure how to fix 0_0

**Comment by hoechenberger** [comment]
@larsoner Can you help?

**Comment by mscheltienne** [comment]
Maybe related to this file: https://github.com/mne-tools/mne-icalabel/blob/ae3a799b919991a96dd04952d838c06543b41d83/index.html#L5-L13

How is it generated?

**Comment by adam2392** [comment]
Ah good find... I think that was leftover from before. I was looking in the main branch, when it was a culprit of the gh-pages branch.

Pushing a manual fix rn

**Comment by adam2392** [comment]
It works! Thanks @mscheltienne !
