### ISSUE TITLE
Point to the MNE installation instructions for getting MNE to run

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-icalabel#51]
We've put a lot of work into creating the MNE installation instructions because there are sooo many potential issues users can run into. Instead of simply suggesting users run `conda install mne` or `pip install mne` here, I'd just say: see the official MNE installation instructions and then come back here again.

Edit: And once we have a `conda-forge` package of MNE-ICALabel, we can include it in the installer and things will become even easier for users!

**Comment by mscheltienne** [comment]
I think we can wait for the conda package and inc. in the installers before refactoring the installation page in the documentation.
