### ISSUE TITLE
JOSS paper for DOI of ICLabel port

### ISSUE THREAD

**Issue by adam2392** [mne-tools/mne-icalabel#59]
https://joss.readthedocs.io/en/latest/submitting.html

**Comment by mscheltienne** [comment]
Thank you, it looks straightforward!

**Comment by adam2392** [comment]
Kay quick summary:

1. we reproduce ICLabel
2. migrate their outdated network -> modern pytorch
3. provide a simple API integrated with MNE-Python
4. enable further improvements and future models

Anyone that's contributed anything to getting this done should of course be an author, so I have: Jacob,Anand,me,Mathieu?

I think since @hoechenberger setup the conda-forge, he should be an author too. Are we missing anyone? 

I think this version will be useful for JOSS until we make significant headway on item 4. Lmk if I missed anything. Will put up a PR for us to all to review together.

**Comment by mscheltienne** [comment]
Agree that @hoechenberger should be added, the setup on conda-forge was a huge time save!
