### ISSUE TITLE
Improve test coverage

### ISSUE THREAD

**Issue by adam2392** [mne-tools/mne-icalabel#93]
Looks like the main parts to improve are `annotations` submodule. We should also ignore the `commands` submodule probably. I think getting those two fixed should bring our test coverage to 90+

<img width="950" alt="Screen Shot 2022-08-05 at 11 01 22 AM" src="https://user-images.githubusercontent.com/3460267/183104994-2e197363-daa3-4aee-b774-687322ee1fa4.png">

**Comment by mscheltienne** [comment]
The display is a bit miss-leading here, the commands module is already ignored: https://github.com/mne-tools/mne-icalabel/blob/a09dddc7e5133b452e31d30c6ca6ac3ca10f4690/pyproject.toml#L168-L178
It was added as part of #88

**Comment by mscheltienne** [comment]
And you need to click on `commands` to 'see' that it's ignored:

<img width="1220" alt="Screenshot 2022-08-05 at 17 05 55" src="https://user-images.githubusercontent.com/73893616/183105964-554a1d16-8873-4a57-8def-c860880c5d05.png">
 
If you remove the module from the `omit` argument, instead of a white square it will show 0%.

**Comment by mscheltienne** [comment]
Now, codecov reports 89.71%. There is definitely a configuration issue, the 93.31% I was getting via `pytest --cov-report term-missing --cov=mne_icalabel mne_icalabel` made more sense.

![image](https://user-images.githubusercontent.com/73893616/183697345-43a72c60-63f3-4d0b-ab49-7e233f886205.png)

**Comment by adam2392** [comment]
Hmm must be something fishy w/ codecov itself then. It seems like its somehow caching the `commands/` submodule, when we told it to omit it.

**Comment by mscheltienne** [comment]
Yes exactly.. The configuration in `pyproject.toml` is:

```
[tool.coverage.run]
branch = true
cover_pylib = false
source = [
    'mne_icalabel',
]
omit = [
    '**/__init__.py',
    'mne_icalabel/commands/*',
    'mne_icalabel/_version.py',
    '**/tests/**',
]

[tool.coverage.report]
exclude_lines = [
    'pragma: no cover',
    'if __name__ == .__main__.:',
]
precision = 2
```

And there is actually an `omit` argument for `[tool.coverage.report]` as well. I did try it in one of the commits of #94 and it did not change anything as far as `Codecov` is concerned. I did not find any configuration set for Codecov, neither at the repository or at the organization level that could explain it.

**Comment by mscheltienne** [comment]
New configuration is handling this better. Coverage at 91.63%.

![Screenshot from 2023-10-27 15-19-20](https://github.com/mne-tools/mne-icalabel/assets/73893616/2f3e949a-5681-4fc6-b02e-bb93d76cea14)

Closing, feel free to re-open if you want to keep this open for the annotation module.
