### ISSUE TITLE
.pt not included in v0.3

### ISSUE THREAD

**Issue by vferat** [mne-tools/mne-icalabel#99]
#### Describe the bug
`FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\ferat\\AppData\\Local\\Continuum\\miniconda3\\envs\\ni39\\lib\\site-packages\\mne_icalabel\\iclabel\\assets\\iclabelNet.pt'`

#### Steps to reproduce
Install version '0.3' via `pip`
then run:
`label_components(raw, ica, method='iclabel')`

#### Additional information
Autocorrection may have change `assets` by `asserts` in `pyproject.toml` ([this line](https://github.com/mne-tools/mne-icalabel/blob/f9ec08ef94e5fd9706a2b6db58e1a8e25a6e8263/pyproject.toml#L124)) so the .pt files are not included.

**Comment by adam2392** [comment]
@mscheltienne FYI.

I guess we'll need to release v0.3.1? or idk if we can re-release v0.3

**Comment by mscheltienne** [comment]
Yes 0.3.1.. thanks Victor.. it's a typo here: https://github.com/mne-tools/mne-icalabel/blob/f9ec08ef94e5fd9706a2b6db58e1a8e25a6e8263/pyproject.toml#L124

I'll fix it now, and check that the build does include the `.pt`.

**Comment by mscheltienne** [comment]
Keeping open until bugfix release.

**Comment by adam2392** [comment]
Might not be able to get to it until later today, if you have time to try to make the release.

**Comment by adam2392** [comment]
Jk I can do it now.

**Comment by adam2392** [comment]
https://pypi.org/project/mne-icalabel/
